FROM openjdk:11
ADD ./target/Student-Profile-Service-0.0.1-SNAPSHOT.jar /usr/src/Student-Profile-Service-0.0.1-SNAPSHOT.jar
WORKDIR usr/src
ENTRYPOINT ["java","-jar", "Student-Profile-Service-0.0.1-SNAPSHOT.jar"]